### ISSUE TITLE
Consider adding a bit more detail to the generation algorithm.

### ISSUE THREAD

**Issue by mikewest** [WICG/change-password-url#2]
I'd suggest being a bit more pedantic about the URL generation algorithm. Perhaps something like:

```
1.  If |origin| is not a [=potentially trustworthy origin=], return failure.

2.  Assert: |origin| is a [=tuple origin=].

3.  Let |url| be a new [=URL=] with values set as follows:
    
    :   [=url/scheme=]
    ::  |origin|'s [=origin/scheme=]
    :   [=url/host=]
    ::  |origin|'s [=origin/host=]
    :   [=url/port=]
    ::  |origin|'s [=origin/port=]
    :   [=url/path=]
    ::  « "`.well-known`", "`change-password`" ».

4.  Return |url|.  
```

@annevk might have opinions about whether it's better to generate URLs this way or by feeding strings into the parser (if the latter, you'll need to serialize the origin before parsing it). This seems clearer to me?

**Comment by annevk** [comment]
What you did there seems fine as long as you control all the relevant fields (or they come from a parsed URL).

**Comment by annevk** [comment]
Except that path is a list so that needs to be a little different.

**Comment by mikewest** [comment]
> Except that path is a list so that needs to be a little different.

Ah. Yes. Editing the original to correct.
