### ISSUE TITLE
Punycode?

### ISSUE THREAD

**Issue by mikewest** [WICG/change-password-url#3]
Origins have an ASCII `domain`, meaning that a host like `example.إختبار` will show up as `example.xn-kgbechtv` in the origin, and therefore in the change-password well-known URL. Is that what we'd like?

**Comment by staabm** [comment]
Couldnt the browser send a spec defined parameter which contains the full url on which the password form was located at the time of storing the password?

**Comment by hober** [comment]
Do you have a preference, @rmondello?

**Comment by annevk** [comment]
For URL the concept, which this document generates, I don't think you have a choice. You do have a choice how you present it though.

**Comment by hober** [comment]
Okay, I added a note in ef1b863 to suggest implementations use IDNA's ToUnicode when/if they display these things.
