### ISSUE TITLE
Consider restricting the target of the redirect to be same-origin

### ISSUE THREAD

**Issue by hober** [WICG/change-password-url#8]
See https://news.ycombinator.com/item?id=18618534

**Comment by jbtule** [comment]
If you restrict the target of the redirect to same origin, it becomes crippled in federated login environments.

**Comment by othermaciej** [comment]
I don't think this is necessary, I agree with this counterpoint: <https://news.ycombinator.com/item?id=18618930>

**Comment by hober** [comment]
@jbtule, @othermaciej okay, I'm sold. Closing.
